#!/bin/bash

rm -rf debs

API_KEY=`cat ~/API_KEY`


mkdir -p debs/stretch

# x64-stretch
docker run -v `pwd`:/mnt --rm debian:stretch /bin/bash -c "cd /mnt; scripts/mkdeb"
scripts/upload_deb build/*.deb $API_KEY stretch testing amd64
mv build/*.deb debs/stretch

# armhf-stretch
docker run -v /usr/bin/qemu-arm-static:/usr/bin/qemu-arm-static -v`pwd`:/mnt --rm arm32v7/debian:stretch /bin/bash -c "cd /mnt; scripts/mkdeb"
scripts/upload_deb build/*.deb $API_KEY stretch testing armhf
mv build/*.deb debs/stretch

# arm64-stretch
docker run -v /usr/bin/qemu-aarch64-static:/usr/bin/qemu-aarch64-static -v`pwd`:/mnt --rm arm64v8/debian:stretch /bin/bash -c "cd /mnt; scripts/mkdeb"
scripts/upload_deb build/*.deb $API_KEY stretch testing arm64
mv build/*.deb debs/stretch


mkdir debs/buster

# x64-buster
docker run -v `pwd`:/mnt --rm debian:buster /bin/bash -c "cd /mnt; scripts/mkdeb"
scripts/upload_deb build/*.deb $API_KEY buster testing amd64
mv build/*.deb debs/buster

# armhf-buster
docker run -v /usr/bin/qemu-arm-static:/usr/bin/qemu-arm-static -v`pwd`:/mnt --rm arm32v7/debian:buster /bin/bash -c "cd /mnt; scripts/mkdeb"
scripts/upload_deb build/*.deb $API_KEY buster testing armhf
mv build/*.deb debs/buster

# arm64-buster
docker run -v /usr/bin/qemu-aarch64-static:/usr/bin/qemu-aarch64-static -v`pwd`:/mnt --rm arm64v8/debian:buster /bin/bash -c "cd /mnt; scripts/mkdeb"
scripts/upload_deb build/*.deb $API_KEY buster testing arm64
mv build/*.deb debs/buster


mkdir debs/bionic

# x64-bionic
docker run -v `pwd`:/mnt --rm ubuntu:bionic /bin/bash -c "cd /mnt; scripts/mkdeb"
scripts/upload_deb build/*.deb $API_KEY bionic testing amd64
mv build/*.deb debs/bionic

# armhf-bionic
docker run -v /usr/bin/qemu-arm-static:/usr/bin/qemu-arm-static -v`pwd`:/mnt --rm arm32v7/ubuntu:bionic /bin/bash -c "cd /mnt; scripts/mkdeb"
scripts/upload_deb build/*.deb $API_KEY bionic testing armhf
mv build/*.deb debs/bionic

# arm64-bionic
docker run -v /usr/bin/qemu-aarch64-static:/usr/bin/qemu-aarch64-static -v`pwd`:/mnt --rm arm64v8/ubuntu:bionic /bin/bash -c "cd /mnt; scripts/mkdeb"
scripts/upload_deb build/*.deb $API_KEY bionic testing arm64
mv build/*.deb debs/bionic
