#!/bin/bash

# Ensure that the script is run as root / sudo
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

# Clean out the old deb files
rm -rf debs

# Process each distro
for DISTRO in debian-stretch debian-buster ubuntu-bionic ubuntu-focal; do
    mkdir -p debs/${DISTRO}

    # Build the docker images for this distro
    for CPU in amd64 armhf arm64; do
        docker build -t wfb-bridge-builder-${CPU}-${DISTRO} -f Dockerfile/${CPU}-${DISTRO} Dockerfile
    done

    # Build debs for each of the architectures
    docker run -v `pwd`:/mnt wfb-bridge-builder-amd64-${DISTRO} /bin/bash -c "cd /mnt; scripts/mkdeb"
    mv build/*.deb debs/${DISTRO}
    if [ ${DISTRO} != "ubuntu-focal" ]; then
        docker run -v /usr/bin/qemu-arm-static:/usr/bin/qemu-arm-static -v`pwd`:/mnt wfb-bridge-builder-armhf-${DISTRO} /bin/bash -c "cd /mnt; scripts/mkdeb"
        mv build/*.deb debs/${DISTRO}
    fi
    docker run -v /usr/bin/qemu-aarch64-static:/usr/bin/qemu-aarch64-static -v`pwd`:/mnt wfb-bridge-builder-arm64-${DISTRO} /bin/bash -c "cd /mnt; scripts/mkdeb"
    mv build/*.deb debs/${DISTRO}
done
