#!/bin/sh

# Ensure that dpkg doesn't prompt for input
export DEBIAN_FRONTEND=noninteractive

# Install required packages
apt-get update
apt-get install -y git libboost-all-dev libpcap-dev python3-pyudev libpcap0.8-dev python3-pip python3-setuptools python3-wheel cmake build-essential

# Ensure the submodules are checked out
git submodule update --init

# Build the deb file and put it in the debs directory
rm -rf build
mkdir -p build debs

# Build the debian package
cd build
cmake -DCMAKE_INSTALL_PREFIX=/ ..
make
cpack
